name: Validate descriptions.yml

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'descriptions.yml'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Validate with yq
        uses: mikefarah/yq@master
        with:
          cmd: yq 'true' descriptions.yml
